### ISSUE TITLE
Insert Spark dataframe into Exasol

### ISSUE THREAD

**Issue by morazow** [exasol/spark-exasol-connector#32]
We should be able to insert Spark dataframe into Exasol table. 

`insert`, `append` or `overwrite` should be possible options.

**Comment by pborah** [comment]
When can i expect this. I have stuck because of it. Unable to push data directly from spark to exasol. Can you help me is there any workaround for this.

**Comment by pborah** [comment]
I am getting below exceptions.

Exception in thread "main" java.sql.SQLException: Feature not supported: user-defined type (TEXT) [line 1, column 51] (Session: 1622792282349682915)
	at com.exasol.jdbc.ExceptionFactory.createSQLException(ExceptionFactory.java:175)
	at com.exasol.jdbc.EXASQLException.getSQLExceptionIntern(EXASQLException.java:50)
	at com.exasol.jdbc.AbstractEXAStatement.execute(AbstractEXAStatement.java:468)
	at com.exasol.jdbc.EXAStatement.execute(EXAStatement.java:278)
	at com.exasol.jdbc.AbstractEXAStatement.exaExecuteLargeUpdate(AbstractEXAStatement.java:618)
	at com.exasol.jdbc.EXAStatement.executeLargeUpdate(EXAStatement.java:413)
	at com.exasol.jdbc.EXAStatement.executeUpdate(EXAStatement.java:468)
	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.createTable(JdbcUtils.scala:859)
	at org.apache.spark.sql.execution.datasources.jdbc.JdbcRelationProvider.createRelation(JdbcRelationProvider.scala:81)
	at org.apache.spark.sql.execution.datasources.SaveIntoDataSourceCommand.run(SaveIntoDataSourceCommand.scala:46)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:70)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:68)

**Comment by morazow** [comment]
Hello @pborah,

Good news! It is almost ready. I am going to push the pull request today and release new version by the end of week or beginning of next week. Please feel to review the PR!

Just a question, could you please share which code / commands resulted in that exception?

**Comment by pborah** [comment]
SparkConf conf = new SparkConf().setAppName("cust data").setMaster("local[*]");
		    SparkSession spark = SparkSession
		    		  .builder()
		    		  .appName("spark")
		    		  .config(conf)
		    		  .getOrCreate();
		
		    
		    Dataset<Row> jdbcDF = spark.read()
					  .format("jdbc")
					  .option("driver", "com.exasol.jdbc.EXADriver")
					  .option("url", "jdbc:exa:10.101.23.12:8563")
					  .option("dbtable", "DEMOQA.spark_data2")
					  .option("user", "sys")
					  .option("fetchsize", 200000)
					  .option("password", "ieee")
					  .load();
		    
		
		jdbcDF.show();
		
		
		Dataset<Row> jdbcDFOrder = jdbcDF.orderBy("4A765BA2-2527-11DF-994B-005056A3157F_0D599CB2-E66E-11E3-A1EE-005056BA260D");
		 
		 System.out.println("Data write in progress");
		 
		 jdbcDF.write()
			.format("jdbc")
			.option("driver", "com.exasol.jdbc.EXADriver")
			.option("url", "jdbc:exa:10.101.23.12:8563")
			.option("dbtable", "DEMOQA.spark_data21")
			.option("batchsize", 2000)
			.option("user", "sys")
			.option("password", "ieee")
			.save();
		 
		  spark.stop();



This is the code where Write operation is failing.

**Comment by morazow** [comment]
Hey @pborah,

You are using Spark "jdbc" datasource not "exasol" :) Using regular `jdbc` source is not a problem at all; however, I might better support you when using this connector which provide `exasol` as a datasource and used parallel (sub) connections. 

Could you please give it a try? Since you are using java api, it will help us also improve or find bugs when used in java application.

However, you exception seems to be because of the 'TEXT' column type. You can check the dataframe schema using `df.printSchema()`, and if any column is with 'TEXT' type change it into Spark 'StringType'.

**Comment by pborah** [comment]
Hey @morazow 
root
 |-- LAST_NAME: string (nullable = true)
 |-- FIRST_NAME: string (nullable = true)
 |-- ADDRESS: string (nullable = true)
 |-- CITY: string (nullable = true)

Above  is the type.  All are type String. But somehow while converting from String to TEXT its broken in Exasol side.

Sure i would definitely love to test ur code n review as well. 
But would test in end of next week. Will be on vacation from tomorrow.

**Comment by morazow** [comment]
@pborah 

Sorry, I cannot immediately see where `TEXT` comes from, I would have to check source from Spark side.

No worries. Great, the insert feature will be released by then. Please do not hesitate to let us know if you face any issues, bugs or have requests!

Best and enjoy your vacations!

**Comment by morazow** [comment]
Fixed in #37.

**Comment by pborah** [comment]
Hello @morazow , I am back. Did u push the latest jar to maven repo ? Please confirm.
  
https://mvnrepository.com/artifact/com.couchbase.client/spark-connector_2.11/2.2.0

**Comment by pborah** [comment]
Hello @morazow 
Created a jar locally  "spark-exasol-connector-assembly-0.2.0.jar"

While performing operation getting below exceptions.  Do i need to add any additional jar ?

Exception in thread "main" java.lang.NoClassDefFoundError: scala/Product$class
	at com.exasol.spark.util.ExasolConfiguration.<init>(ExasolConfiguration.scala:42)
	at com.exasol.spark.util.ExasolConfiguration$.apply(ExasolConfiguration.scala:60)
	at com.exasol.spark.DefaultSource.createManager(DefaultSource.scala:202)
	at com.exasol.spark.DefaultSource.createRelation(DefaultSource.scala:82)
	at org.apache.spark.sql.execution.datasources.SaveIntoDataSourceCommand.run(SaveIntoDataSourceCommand.scala:46)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:70)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:68)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.doExecute(commands.scala:86)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$execute$1(SparkPlan.scala:131)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:155)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:152)
	at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:127)
	at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:80)
	at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:80)
	at org.apache.spark.sql.DataFrameWriter.$anonfun$runCommand$1(DataFrameWriter.scala:668)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:78)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:125)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:73)
	at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:668)
	at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:281)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:270)
	at com.aera.spark.ReadWriteExasolAssembly.main(ReadWriteExasolAssembly.java:68)
Caused by: java.lang.ClassNotFoundException: scala.Product$class
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 23 more

**Comment by morazow** [comment]
Hello @pborah,

Welcome back! 

Yes, `0.2.0`  is latest version, please find the dependency link [here](https://mvnrepository.com/artifact/com.exasol/spark-connector_2.11/0.2.0). (Above link points to couchbase connecter).

I am assuming you are using the connector from Java Spark application? From the error it seems like it cannot find the Scala library. 

You can add [Scala 2.11.x library](https://mvnrepository.com/artifact/org.scala-lang/scala-library/2.11.12) as dependency. Additionally, you can also build the fat jar, after cloning inside the repository folder, run `./sbtx assembly`. This will create a all dependencies included jar inside `target/scala-2.11/` folder. Then this can be provided to the Java application.

I know that the Spark dependencies are intentionally excluded from connector since they are provided at runtime when submitting the Spark application. I will check again if the Scala libs should be defined as requirement at compile time.

Please let us know you findings!

Best

**Comment by pborah** [comment]
Hello @morazow 

I am getting below exceptions now. Any idea whats missing here. 


 jdbcDFOrder.write()
		  .mode("overwrite")
		  .option("host", "100.121.23.110")
		  .option("port", "8563")
		  .option("username", "sys")
		  .option("password", "******")
		  .option("create_table", "true")
		  .option("table", "DEMOQA.spark_data212")
		  .format("exasol")
		  .save();


Exception in thread "main" java.lang.NoSuchMethodError: com.exasol.jdbc.EXAConnection.EnterParallel(I)I
	at com.exasol.spark.util.ExasolConnectionManager.initParallel(ExasolConnectionManager.scala:55)
	at com.exasol.spark.writer.ExasolWriter.startParallel(ExasolWriter.scala:48)
	at com.exasol.spark.DefaultSource.saveDFTable(DefaultSource.scala:130)
	at com.exasol.spark.DefaultSource.createRelation(DefaultSource.scala:92)
	at org.apache.spark.sql.execution.datasources.SaveIntoDataSourceCommand.run(SaveIntoDataSourceCommand.scala:45)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:70)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:68)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.doExecute(commands.scala:86)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:131)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:127)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeQuery$1.apply(SparkPlan.scala:155)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:152)
	at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:127)
	at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:80)
	at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:80)
	at org.apache.spark.sql.DataFrameWriter$$anonfun$runCommand$1.apply(DataFrameWriter.scala:668)
	at org.apache.spark.sql.DataFrameWriter$$anonfun$runCommand$1.apply(DataFrameWriter.scala:668)
	at org.apache.spark.sql.execution.SQLExecution$$anonfun$withNewExecutionId$1.apply(SQLExecution.scala:78)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:125)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:73)
	at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:668)
	at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:276)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:270)
	at com.aera.spark.ReadWriteExasolAssembly.main(ReadWriteExasolAssembly.java:70)

**Comment by morazow** [comment]
Hello @pborah,

This seems like missing Exasol jdbc dependency.

Could you please add these also as dependency? For example, pom.xml:

```xml
<repository>
    <id>maven.exasol.com</id>
    <url>https://maven.exasol.com/artifactory/exasol-releases</url>
</repository>

<dependency>
    <groupId>com.exasol</groupId>
    <artifactId>exasol-jdbc</artifactId>
    <version>6.0.13</version>
</dependency>
```

**Comment by morazow** [comment]
Hello @pborah,

Were you able to evaluate the connector?

Please do not hesitate to let me know if you have any issues.

**Comment by pborah** [comment]
Yes Its working fine. Thanks for ur help.
