### ISSUE TITLE
Error: com.exasol.spark.DefaultSource does not allow create table as select.

### ISSUE THREAD

**Issue by xibux-repo** [exasol/spark-exasol-connector#57]
Hi, 

I try to use the connector in Pyspark to write data from Hadoop (2.4) by (selecting a hive table) to Exasol. The table is not created beforehand at all, got following error message about '**not allow create table as select**'. Hope somebody can help me further. Thank you very much!

My code: 
`df_hdfs = spark.sql("select * from {}".format(hive_table))
df_hdfs.printSchema()
df_hdfs.write.mode("overwrite")\
    .option("username", exa_user) \
    .option("password", exa_pwd)  \
    .option("table", "MY_SCHEMA.MY_TABLE") \
    .format("exasol") \
    .save()`

The schema of the dataframe is
'root
 |-- CAMPAIGN_ID: string (nullable = true)
 |-- ATTRIBUTION_LEVEL: string (nullable = true)
 |-- EL_AFFILIATE_ID: string (nullable = true)
 |-- EL_EINSPRUNGSLINK: string (nullable = true)
 |-- EL_KAMPAGNENNAME: string (nullable = true)
 |-- EL_KANAL: string (nullable = true)
 |-- EL_KOOP_PLATZIERUNG: string (nullable = true)
 |-- EL_NL_ECMKAT: string (nullable = true)
 |-- EL_NL_FLAECHE: string (nullable = true)
 |-- EL_NL_TYP: string (nullable = true)
 |-- EL_NL_VARIANTE: string (nullable = true)
 |-- EL_PARTNER: string (nullable = true)
 |-- EL_SEM_ADGROUP: string (nullable = true)
 |-- EL_SEM_ANZEIGEURL: string (nullable = true)
 |-- EL_SEM_HEADLINE: string (nullable = true)
 |-- EL_SEM_KAMPAGNE: string (nullable = true)
 |-- EL_SEM_KEYWORD: string (nullable = true)
 |-- EL_SEM_KONTO: string (nullable = true)
 |-- EL_SEM_MATCHTYPE: string (nullable = true)
 |-- EL_SEM_SORTIMENT: string (nullable = true)
 |-- EL_SEM_TEXTLINE1: string (nullable = true)
 |-- EL_SEM_TEXTLINE2: string (nullable = true)
 |-- EL_UNTERPARTNER: string (nullable = true)
 |-- EL_WERBEMITTEL: string (nullable = true)
 |-- EL_WERBEMITTEL_FORMAT: string (nullable = true)
 |-- EL_WERBEMITTEL_MOTIV: string (nullable = true)
 |-- EL_WERBEMITTEL_THEMA: string (nullable = true)
 |-- EL_WERBEMITTEL_TYP: string (nullable = true)
 |-- IWL: string (nullable = true)
 |-- LINK_NAME: string (nullable = true)
 |-- PXID: string (nullable = true)
 |-- KATEGORIE: string (nullable = true)
`
**Error**: 

': **java.lang.RuntimeException: com.exasol.spark.DefaultSource does not allow create table as select**.
	at scala.sys.package$.error(package.scala:27)
	at org.apache.spark.sql.execution.datasources.DataSource.planForWriting(DataSource.scala:526)
	at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:281)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:270)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)`

**Comment by morazow** [comment]
Hello @xibux-repo,

Thanks for reporting the issue!

From quick look, you should also set `create_table` to `true` to create table if it does not exist.

```
df_hdfs.write.mode("overwrite").option("table", ...).option("create_table", "true")....
```

Please let us know if the issue still persists.

**Comment by xibux-repo** [comment]
Thank you so much! At least I didn't get the same error, I got some 'data type' problem:  

` java.sql.SQLException: Cannot handle data type: 2005
	at com.exasol.jdbc.AbstractEXAPreparedStatement.createNull(AbstractEXAPreparedStatement.java:938)
	at com.exasol.jdbc.AbstractEXAPreparedStatement.setNull(AbstractEXAPreparedStatement.java:887)
	at com.exasol.spark.writer.ExasolWriter.insertPartition(ExasolWriter.scala:92)
	at com.exasol.spark.DefaultSource$$anonfun$saveDFTable$1.apply(DefaultSource.scala:133)
	at com.exasol.spark.DefaultSource$$anonfun$saveDFTable$1.apply(DefaultSource.scala:133)
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$28.apply(RDD.scala:935)
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$28.apply(RDD.scala:935)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2101)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2101)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:121)
	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:408)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)`

But i saw there is an issue already posted [here](https://github.com/exasol/spark-exasol-connector/issues/46). Since which version is this bug fixed? I'm using the spark2.4.3 with connector version assembly-0.2.0-2-g0164ecf. Thanks!

**Comment by xibux-repo** [comment]
Thanks a lot! @morazow . I created the jar for the scalar version 2.11.12 what we have now. After testing i got following error: 
`Caused by: java.io.InvalidClassException: com.exasol.spark.writer.ExasolWriter; local class incompatible: stream classdesc serialVersionUID = 3001495094914647942, local class serialVersionUID = -185775931428982968`

Hope you can help me further. Thank you!

**Comment by morazow** [comment]
Hello @xibux-repo,

Sorry for late reply.

Did you run spark-exasol-connector assembly also with scala version 2.11.12? The error seems to Scala (or Spark) version compatibility issue.

These issues occur, for example, when you compile the spark-exasol-connector with Scala version 2.12+ and run in an environment that uses Scala version 2.11+.

Could you please create assembled jar using Scala version 2.11 and test again?

You can add Scala version when running assembly command:

```sh
./sbtx ++2.11.12 assembly
```

**Comment by xibux-repo** [comment]
Hi @morazow,

no problem. I did run it for the scala version 2.11.12 in spark 2.4.3. The error I posted in the last post is the error with the same version, this is why it confuses me a lot with the "imcompatible".

**Comment by morazow** [comment]
Hmm that is strange. Could you please also ensure that previous jars are removed from Spark cluster? 

Sorry, currently I am occupied with other tasks, if the error still persists I can have a look into it when I am available again.

**Comment by xibux-repo** [comment]
@morazow It was exactly this problem. After removing the old jar, it works. @3cham helped me a lot! Thank you very much @morazow @3cham! Therefore we can close this issue.

Best wishes
Xibin

**Comment by morazow** [comment]
Hey @xibux-repo,

Great to hear that! @3cham and also @jpizagno could both help you! 

However, feel free to open an issue if you face any other challenges. It might help others also.
