### ISSUE TITLE
Kerberos auth

### ISSUE THREAD

**Issue by nikoki** [exasol/spark-exasol-connector#71]
Hi,
Is kerberos auth supported?
Since we switched to Kerberos i am receiving these errors:

Exception in thread "main" org.apache.spark.SparkException: Job aborted due to stage failure: Task 2 in stage 77.0 failed 4 times, most recent failure: Lost task 2.3 in stage 77.0 (TID 5711, CLUSTER_NAME, executor 40): **com.exasol.jdbc.ConnectFailed: Connection refused (Connection refused)**

Thanks!

**Comment by morazow** [comment]
Sorry, I could not reply earlier. I was on a vacation past two weeks.

Unfortunately, the spark exasol connector does not support kerberos
at the moment.

But since your spark cluster is kerberos enabled (and not exasol cluster)
the connection still should work?

Do you have more logs, for example the Ipv4 addresses the Spark tasks
connecting?

**Comment by nikoki** [comment]
Sorry for the late response.

After some further debugging it looks like the problem is not created by Kerberization of the server. The error message (Connection refused) lead me to think that. Let me explain a bit further.

First of all, I updated the lib version to 0.3.0 - we were using 0.2.1 previously.

During the debugging process, I ran the same job on the same data and produced deterministic failure in the code. My code was pushing 3 tables to Exasol using the connector -  and the problem always occurred when writing second of the 3 tables.
This proved that Kerberization had nothing to do with the problem, since first and third table were working fine.
On the other hand, error message was confusing. For the same job, same data and same pipeline i received these 2 messages interchangeably without any observable pattern:

1. Exception in thread "main" org.apache.spark.SparkException: Job aborted due to stage failure: Task 2 in stage 77.0 failed 4 times, most recent failure: Lost task 2.3 in stage 77.0 (TID 5711, CLUSTER_NAME, executor 40): com.exasol.jdbc.ConnectFailed: Connection refused (Connection refused)

2. Exasol failed: Job aborted due to stage failure: Task 2 in stage 78.0 failed 4 times, most recent failure: Lost task 2.3 in stage 78.0 (TID 5577, CLUSTER_NAME, executor 20): org.apache.spark.memory.SparkOutOfMemoryError: Unable to acquire 65536 bytes of memory, got 0


It turned out that due to the bug in our scripts the data volume that was being pushed to Exasol was several times larger than usual.
Once we fixed the bug everything started working fine.
So, you can close this issue, but the thing that is interesting is that second message helped debug the problem - it suggests that the data is too big (for the memory), but the first message did not indicate that, although the root cause is the same.

Thanks, and sorry for your trouble!

**Comment by kundacina-m** [comment]
Hi,
I'm experiencing similar issue and I don't think there is issue with data volume.
Dataframe that I'm trying to insert into Exasol is 9row x 35col size with fields that are mostly null or strings that do not exceed 50 characters. What is pretty odd is that somehow table is actually created along with appropriate columns, but there is no data inserted.

Here is stacktrace:

```
Job aborted due to stage failure: Task 3 in stage 118.0 failed 4 times, most recent failure: Lost task 3.3 in stage 118.0 (TID 7369, CLUSTER_NAME, executor 3): org.apache.spark.memory.SparkOutOfMemoryError: Unable to acquire 572 bytes of memory, got 0
	at org.apache.spark.memory.MemoryConsumer.throwOom(MemoryConsumer.java:157)
	at org.apache.spark.memory.MemoryConsumer.allocatePage(MemoryConsumer.java:119)
	at org.apache.spark.util.collection.unsafe.sort.UnsafeExternalSorter.acquireNewPageIfNecessary(UnsafeExternalSorter.java:383)
	at org.apache.spark.util.collection.unsafe.sort.UnsafeExternalSorter.insertRecord(UnsafeExternalSorter.java:407)
	at org.apache.spark.sql.execution.UnsafeExternalRowSorter.insertRow(UnsafeExternalRowSorter.java:135)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage3.sort_addToSorter_0$(Unknown Source)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage3.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$13$$anon$1.hasNext(WholeStageCodegenExec.scala:636)
	at org.apache.spark.sql.execution.RowIteratorFromScala.advanceNext(RowIterator.scala:83)
	at org.apache.spark.sql.execution.joins.SortMergeJoinScanner.advancedBufferedToRowWithNullFreeJoinKey(SortMergeJoinExec.scala:811)
	at org.apache.spark.sql.execution.joins.SortMergeJoinScanner.<init>(SortMergeJoinExec.scala:686)
	at org.apache.spark.sql.execution.joins.SortMergeJoinExec$$anonfun$doExecute$1.apply(SortMergeJoinExec.scala:213)
	at org.apache.spark.sql.execution.joins.SortMergeJoinExec$$anonfun$doExecute$1.apply(SortMergeJoinExec.scala:150)
	at org.apache.spark.rdd.ZippedPartitionsRDD2.compute(ZippedPartitionsRDD.scala:89)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.rdd.CoalescedRDD$$anonfun$compute$1.apply(CoalescedRDD.scala:100)
	at org.apache.spark.rdd.CoalescedRDD$$anonfun$compute$1.apply(CoalescedRDD.scala:99)
	at scala.collection.Iterator$$anon$12.nextCur(Iterator.scala:435)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:441)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:409)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:409)
	at com.exasol.spark.writer.ExasolWriter.insertPartition(ExasolWriter.scala:82)
	at com.exasol.spark.DefaultSource$$anonfun$saveDFTable$1.apply(DefaultSource.scala:140)
	at com.exasol.spark.DefaultSource$$anonfun$saveDFTable$1.apply(DefaultSource.scala:140)
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$28.apply(RDD.scala:935)
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$28.apply(RDD.scala:935)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2101)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2101)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:121)
	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:408)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1405)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by morazow** [comment]
Hello @nikoki, @kundacina-m,

Thanks for your feedback! We highly appreciate it!

@nikoki, 

It is great that you were able to solve the issue! I agree, the error message does not help very much here. From my understanding, one of the Spark tasks fails due to memory issues. 

Meanwhile, on the Exasol side the waiting JDBC subconnection timeout reaches and it closes the connection. Please keep in mind this is problem for all parallel connections, not to single one. In this case, you should see the `"Connection was lost"` exceptions for the first attempt. You could check that this exception is thrown early on the first attempt of tasks.

The above connection refused exception is for the following attempts when task tries to connect to the closed Exasol JDBC subconnection.

@kundacina-m 

I guess the error is not related to Exasol, but to Spark task memory. From the exception message I see that it does not reach to save action yet. I also see that you are doing join, please check that the join key is not skewed. Since a join for a key is performed in a one Spark task, check that a single key does not contain majority of the values.

Additionally, you can increase memory of executor and decrease the executor cores per node. 

For example, start spark-submit or spark-shell with similar parameters:

```
 --executor-cores 5 \
 --executor-memory 34G \
 --conf spark.yarn.executor.memoryOverhead=3891M
```

This will start 5 tasks per executor, each with ~6.8G memory. I have also added memory overhead for executor. You can also set the `--num-executors` parameter to control how many executors are started. This will allow to balance memory of a cluster node. 

I hope this is helpful, please let us know if there are issues or questions.

Best

**Comment by morazow** [comment]
Hey all,

I am going to close this issue. Please open a new issue if there are still questions.
