### ISSUE TITLE
Issue Using multiple Select while loading tables

### ISSUE THREAD

**Issue by AlessioMagitteri** [exasol/spark-exasol-connector#74]
Hello,

I have just started to work with Exasol and I am trying to migrate my spark-scala code from the old database to Exasol. 

Spark-exasol-connector version: 0.3.0 (I have done a try also using the 0.2.0)
Spark version: spark-sql_2.11:2.1.1

In the case I run a single query to read a single table using

"SELECT * FROM schema.table"

I can do whatever I want and save the results. As soon as I try to do something slightly more complex as could be:

val query1 = "SELECT * FROM XXX.table1"

val df1 = sparkSession.read
                                   .format("exasol")
                                   .option("host", myHost)
                                   .option("port", myPort)
                                  .option("username", myUser)
                                  .option("password", myPwd)
                                  .option("query", query1)
                                  .load()

val query2 = "SELECT * FROM XXX.table2"

val df2 = sparkSession.read
                                   .format("exasol")
                                   .option("host", myHost)
                                   .option("port", myPort)
                                  .option("username", myUser)
                                  .option("password", myPwd)
                                  .option("query", query2)
                                  .load()

val finalDf = df1.join(df2)
finalDf.write
           .mode("append")
          .option("host", myHost)
          .option("port", myPort)
          .option("username",  myUser)
          .option("password", myPwd)
         .option("table", myExasolTable)
         .format("exasol")
         .save()

I receive the following error:

**_20/08/25 09:04:13 ERROR TaskSetManager: Task 0 in stage 3.0 failed 4 times; aborting job
org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 3.0 failed 4 times, most recent failure: Lost task 0.3 in stage 3.0 (TID 41, 172.30.133.132, executor 0): com.exasol.jdbc.ConnectFailed: connect timed out
at com.exasol.jdbc.AbstractEXAConnection.setupConnection(AbstractEXAConnection.java:1299)
at com.exasol.jdbc.AbstractEXAConnection.Connect(AbstractEXAConnection.java:1166)
at com.exasol.jdbc.AbstractEXAConnection.<init>(AbstractEXAConnection.java:333)
at com.exasol.jdbc.EXAConnection.<init>(EXAConnection.java:36)
at com.exasol.jdbc.EXADriver.connect(EXADriver.java:228)
at java.sql.DriverManager.getConnection(DriverManager.java:664)
at java.sql.DriverManager.getConnection(DriverManager.java:247)
at com.exasol.spark.util.ExasolConnectionManager$.createConnection(ExasolConnectionManager.scala:210)
at com.exasol.spark.util.ExasolConnectionManager$.makeConnection(ExasolConnectionManager.scala:226)
at com.exasol.spark.util.ExasolConnectionManager.subConnection(ExasolConnectionManager.scala:71)
at com.exasol.spark.rdd.ExasolRDD.compute(ExasolRDD.scala:155)
at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
at org.apache.spark.scheduler.Task.run(Task.scala:108)
at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:335)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)_**

I have also tried to merge the SELECT of the two tables in on single big SELECT without any change.

In addition

1. The connection between spark and exasol is established because I don't have any issue to print the schema of each table using df1.printSchema() and df2.printSchema().
2. The port are properly opened both the main one and the ports for the sub-connections (20000-21000)
3. spark.exasol.max_nodes=2 is set to the same value used in spark-shell script (--executor-cores=2)

Do you have any suggestion how to fix it?

Thanks for your support.

Best,
Alessio

**Comment by morazow** [comment]
Hello @AlessioMagitteri ,

Thanks for the feedback!

Unfortunately, we cannot pushdown the Spark joins to the Exasol at the moment. 

In the above example, Spark is going to plan single execution. But you have two datasource from Exasol, only one of the is going to be handled, the other one will timeout. 

Could you please try by using [`UNION ALL`](https://docs.exasol.com/sql/table_operators.htm) Exasol operation?

```scala
val query = "SELECT * ( (SELECT FROM XXX.table1) UNION ALL (SELECT * FROM XXX.table2) )"
```

You should perform all the possible computations at the Exasol side and load only the required results into Exasol. Then continue inside Spark to perform Spark specific transformations or joins with other datasources.

**Comment by morazow** [comment]
Hello @AlessioMagitteri,

Since we resolved the issue from the Support channel, I am going to close this ticket.

Thanks again for your feedback and collaboration! Please let us know if there are any other issues.
